# Generated by Django 5.0.4 on 2024-06-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_publisher_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='cover',
            new_name='profile_picture',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='cover/'),
        ),
    ]
